# Generated by Django 4.2.6 on 2023-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_bloguser_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_user',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years',
            field=models.IntegerField(default=18),
        ),
    ]
