# Generated by Django 4.2.6 on 2023-11-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_user',
            field=models.TextField(default='Не указано'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='Не указано', max_length=100),
        ),
    ]
