# Generated by Django 4.2.6 on 2023-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relog', '0004_bloguser_date_bloguser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
