# Generated by Django 4.2.6 on 2023-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
