# Generated by Django 4.2.6 on 2023-12-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitys', '0002_community_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(default='Не указано', max_length=100)),
                ('about_community', models.TextField(default='Не указано')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitys.community')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers_community', to='communitys.community')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitys.community')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_posts_community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
