# Generated by Django 4.2.6 on 2023-12-10 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitys', '0003_communityprofile_blogcommunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
